#!/bin/bash

echo "🔍 Verificando Secrets configurados no Supabase..."
echo ""

# Listar secrets
echo "📋 Listando todos os secrets..."
npx supabase secrets list

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Secrets OBRIGATÓRIOS para kiwify-api:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. KIWIFY_CLIENT_ID"
echo "2. KIWIFY_CLIENT_SECRET"
echo "3. KIWIFY_ACCOUNT_ID"
echo ""
echo "Se algum destes NÃO aparecer na lista acima, configure:"
echo ""
echo "npx supabase secrets set KIWIFY_CLIENT_ID=\"4c747409-c212-45d1-aaf9-4a5d43dac808\""
echo "npx supabase secrets set KIWIFY_CLIENT_SECRET=\"seu-secret-aqui\""
echo "npx supabase secrets set KIWIFY_ACCOUNT_ID=\"av8qNBGVVoyVD75\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Secrets RECOMENDADOS (para funcionar 100%):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4. SUPABASE_URL"
echo "5. SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "npx supabase secrets set SUPABASE_URL=\"https://keawapzxqoyesptwpwav.supabase.co\""
echo "npx supabase secrets set SUPABASE_SERVICE_ROLE_KEY=\"sua-service-role-key\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️ Após configurar os secrets, você DEVE fazer redeploy:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npx supabase functions deploy kiwify-api"
echo "npx supabase functions deploy kiwify-sync"
echo ""
